name: Update Snapshots

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: choice
        options:
          - macos-latest
          - windows-latest
          - ubuntu-latest

jobs:
  update-snapshots:
    name: Update Snapshots
    runs-on: ${{ inputs.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Fetch Test Branches
        run: git fetch origin test/javascript:test/javascript
      - name: Install tarpaulin
        uses: actions-rs/install@v0.1
        continue-on-error: true
        with:
          crate: cargo-insta

      - run: cargo insta test --accept
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update snapshots
